# .github/workflows/test-action.yml
name: Test Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom Docker action
        uses: ./ # Points to the local action
        with:
          name: "Marino"
